version: "3.8"
services:
  sqlserver:
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Test.1234"
      MSSQL_PID": "Express"
    ports:
      - "1433:1433"
